import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../core/theme';

export function makeTalkStyles(c: ThemePalette) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: c.bg,
      padding: 16,
    },
    sectionTitle: {
      color: c.textPrimary,
      fontSize: 15,
      fontWeight: '700',
      marginBottom: 12,
    },
    groupsScroll: {
      maxHeight: 52,
      marginBottom: 16,
    },
    groupsContainer: {
      paddingRight: 16,
      alignItems: 'center',
    },
    groupPill: {
      backgroundColor: c.surface,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: c.border,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginRight: 10,
    },
    groupPillActive: {
      backgroundColor: c.accent,
      borderColor: c.accent,
    },
    groupText: {
      color: c.textMuted,
      fontSize: 13,
      fontWeight: '700',
    },
    groupTextActive: {
      color: c.textOnAccent,
    },
    centerCard: {
      flex: 1,
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 18,
      borderWidth: 1,
      borderColor: c.border,
      justifyContent: 'space-between',
    },
    selectedLabel: {
      color: c.textSecondary,
      fontSize: 13,
      marginBottom: 14,
    },
    pushButtonWrapper: {
      width: 262,
      height: 262,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 14,
    },
    pushButtonRing: {
      position: 'absolute',
      width: 262,
      height: 262,
      borderRadius: 131,
      borderWidth: 3,
      borderColor: c.accent,
    },
    pushButton: {
      width: 240,
      height: 240,
      alignSelf: 'center',
      borderRadius: 120,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: c.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.16,
      shadowRadius: 20,
      elevation: 8,
    },
    pushButtonDisabled: {
      opacity: 0.5,
    },
    speakerName: {
      color: c.textOnAccent,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 12,
    },
    buttonSpeakerName: {
      color: c.textOnAccent,
      fontSize: 14,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 12,
    },
    voiceMeterContainer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'center',
      gap: 3,
      height: 36,
      marginBottom: 16,
      paddingHorizontal: 20,
    },
    voiceBar: {
      flex: 1,
      borderRadius: 2,
      minHeight: 3,
      backgroundColor: 'rgba(255,255,255,0.15)',
    },
    pushButtonText: {
      color: c.textOnAccent,
      fontSize: 20,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 6,
    },
    pushButtonStatus: {
      color: c.textOnAccent,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.2,
      marginBottom: 10,
    },
    voiceLevelRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'center',
      gap: 6,
      marginBottom: 10,
      minHeight: 20,
    },
    voiceLevelBar: {
      width: 10,
      height: 10,
      backgroundColor: c.inputBg,
      borderRadius: 4,
      opacity: 0.35,
    },
    voiceLevelBarActive: {
      backgroundColor: c.success,
    },
    pushButtonMeta: {
      color: c.textMuted,
      fontSize: 12,
      textAlign: 'center',
    },
    pushStatus: {
      color: c.textSecondary,
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 22,
    },
    modeRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 16,
    },
    modePill: {
      flex: 1,
      backgroundColor: c.bg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 10,
    },
    modePillActive: {
      backgroundColor: c.accent,
      borderColor: c.accent,
    },
    modeText: {
      color: c.textMuted,
      fontSize: 13,
      fontWeight: '700',
    },
    modeTextActive: {
      color: c.textOnAccent,
    },
    actionRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    actionButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    micButton: {
      backgroundColor: c.secondary,
      marginBottom: 12,
    },
    micStatusText: {
      color: c.success,
      fontSize: 12,
      textAlign: 'center',
      marginBottom: 12,
    },
    micErrorText: {
      color: c.error,
      fontSize: 12,
      textAlign: 'center',
      marginBottom: 12,
    },
    startButton: {
      backgroundColor: c.primary,
    },
    endButton: {
      backgroundColor: c.error,
    },
    actionButtonText: {
      color: c.textOnAccent,
      fontWeight: '700',
      fontSize: 14,
    },
    mockOverlay: {
      position: 'absolute',
      bottom: 18,
      left: 18,
      right: 18,
      zIndex: 10,
    },
    mockCard: {
      backgroundColor: c.bg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 14,
    },
    mockHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    mockTitle: {
      color: c.textPrimary,
      fontWeight: '700',
    },
    mockCloseButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: c.surface,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    mockCloseText: {
      color: c.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    mockSectionLabel: {
      color: c.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    mockRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    mockButton: {
      flex: 1,
      borderRadius: 10,
      paddingVertical: 11,
      justifyContent: 'center',
      alignItems: 'center',
    },
    mockButtonPrimary: {
      backgroundColor: c.primary,
    },
    mockButtonDanger: {
      backgroundColor: c.error,
    },
    mockButtonReset: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
    },
    mockButtonText: {
      color: c.textOnAccent,
      fontSize: 12,
      fontWeight: '800',
    },
  });
}
