import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../core/theme';

export function makeTalkStyles(c: ThemePalette) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: c.bg,
      padding: 16,
    },
    groupsScroll: {
      height: 72,
      marginBottom: 4,
    },
    groupsContainer: {
      paddingRight: 16,
      alignItems: 'center',
    },
    groupCol: {
      alignItems: 'center',
      marginRight: 14,
    },
    groupAvatar: {
      width: 60,
      height: 60,
      borderRadius: 30,
      borderWidth: 2.5,
      borderColor: c.border,
      backgroundColor: c.surface,
      justifyContent: 'center',
      alignItems: 'center',
    },
    groupAvatarWrap: {
      position: 'relative',
    },
    incomingBadge: {
      position: 'absolute',
      top: -3,
      left: -3,
      width: 66,
      height: 66,
      borderRadius: 33,
      borderWidth: 3,
      borderColor: '#ef4444',
    },
    groupAvatarActive: {
      backgroundColor: c.accent,
      borderColor: c.accent,
    },
    groupLabel: {
      color: c.textSecondary,
      fontSize: 10,
      fontWeight: '700',
      marginTop: 2,
      textAlign: 'center',
    },
    groupLabelActive: {
      color: c.textPrimary,
    },
    groupIconWrap: {
      flexDirection: 'row',
      alignItems: 'flex-end',
    },
    groupIconPerson: {
      alignItems: 'center',
    },
    groupIconHead: {
      width: 16,
      height: 16,
      borderRadius: 8,
    },
    groupIconBody: {
      width: 20,
      height: 10,
      borderRadius: 3,
      marginTop: 2,
    },
    centerCard: {
      flex: 25,
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 18,
      borderWidth: 1,
      borderColor: c.border,
    },
    centerBody: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    selectedRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    selectedLabel: {
      color: c.textPrimary,
      fontSize: 16,
      fontWeight: '800',
    },
    menuToggleButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    menuToggleIcon: {
      color: c.textPrimary,
      fontSize: 18,
      fontWeight: '700',
      lineHeight: 20,
    },
    mockToggleMini: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    mockToggleMiniText: {
      fontSize: 14,
      color: c.textMuted,
    },
    menuOverlayContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 20,
    },
    menuBackdrop: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    menuCard: {
      position: 'absolute',
      top: 52,
      left: 0,
      right: 0,
      backgroundColor: c.bg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 8,
      zIndex: 21,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 12,
    },
    menuItem: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 10,
    },
    menuItemText: {
      color: c.textPrimary,
      fontSize: 14,
      fontWeight: '600',
    },
    pushButtonWrapper: {
      width: 270,
      height: 270,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 14,
    },
    // Dış yükleme ve durum halkası
    pushButtonRing: {
      position: 'absolute',
      width: 266,
      height: 266,
      borderRadius: 133,
      borderWidth: 2,
      borderColor: c.accent,
      opacity: 0.8,
    },
    pushButton: {
      width: 230,
      height: 230,
      alignSelf: 'center',
      borderRadius: 115,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      // Sabit ve temiz bir border, derinlik hissi için şık gölgeler
      borderColor: 'rgba(255, 255, 255, 0.1)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.24,
      shadowRadius: 16,
      elevation: 10,
    },
    pushButtonDisabled: {
      opacity: 0.4,
    },
    buttonSpeakerName: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: 8,
    },
    voiceMeterContainer: {
      flexDirection: 'row',
      alignItems: 'center', // Barları ortalayarak daha modern bir görünüm elde edebiliriz
      justifyContent: 'center',
      gap: 4,
      height: 40,
      marginBottom: 12,
      paddingHorizontal: 30,
    },
    voiceBar: {
      flex: 1,
      borderRadius: 3,
      minHeight: 4,
    },
    pushButtonStatus: {
      color: '#ffffff',
      fontSize: 22,
      fontWeight: '700',
      letterSpacing: 0.5,
      textAlign: 'center',
    },
    speakerName: {
      color: c.textOnAccent,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 12,
    },

    pushButtonText: {
      color: c.textOnAccent,
      fontSize: 20,
      fontWeight: '800',
      textAlign: 'center',
      marginBottom: 6,
    },

    voiceLevelRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'center',
      gap: 6,
      marginBottom: 10,
      minHeight: 20,
    },
    voiceLevelBar: {
      width: 10,
      height: 10,
      backgroundColor: c.inputBg,
      borderRadius: 4,
      opacity: 0.35,
    },
    voiceLevelBarActive: {
      backgroundColor: c.success,
    },
    pushButtonMeta: {
      color: c.textMuted,
      fontSize: 12,
      textAlign: 'center',
    },
    pushStatus: {
      color: c.textSecondary,
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 22,
    },
    modeRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 16,
    },
    modeRowHidden: {
      opacity: 0,
      pointerEvents: 'none',
    },
    modePill: {
      flex: 1,
      backgroundColor: c.bg,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: c.border,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    modePillActive: {
      backgroundColor: c.accent,
      borderColor: c.accent,
      shadowColor: c.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 5,
    },
    modePillDisabled: {
      opacity: 0.4,
    },
    modeText: {
      color: c.textSecondary,
      fontSize: 13,
      fontWeight: '800',
    },
    modeTextActive: {
      color: c.textOnAccent,
      fontSize: 14,
    },
    actionRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: -12
    },
    actionButton: {
      flex: 1,
      flexDirection: 'row',
      paddingVertical: 8,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 6,
    },
    startButton: {
      backgroundColor: c.primary,
    },
    endButton: {
      backgroundColor: c.error,
    },
    actionButtonDisabled: {
      opacity: 0.35,
    },
    actionButtonText: {
      color: c.textOnAccent,
      fontWeight: '700',
      fontSize: 14,
    },
    actionButtonTextDisabled: {
      opacity: 0.5,
    },
    actionButtonIcon: {
      fontSize: 18,
    },
    mockOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 20,
      justifyContent: 'flex-end',
    },
    mockBackdrop: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    mockCard: {
      backgroundColor: c.bg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 14,
      marginHorizontal: 16,
      marginBottom: 16,
    },
    mockHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    mockTitle: {
      color: c.textPrimary,
      fontWeight: '700',
    },
    mockCloseButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: c.surface,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    mockCloseText: {
      color: c.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    mockSectionLabel: {
      color: c.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 8,
    },
    mockRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    mockButton: {
      flex: 1,
      borderRadius: 10,
      paddingVertical: 11,
      justifyContent: 'center',
      alignItems: 'center',
    },
    mockButtonPrimary: {
      backgroundColor: c.primary,
    },
    mockButtonDanger: {
      backgroundColor: c.error,
    },
    mockButtonReset: {
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
    },
    mockButtonText: {
      color: c.textOnAccent,
      fontSize: 12,
      fontWeight: '800',
    },
  });
}
